
# spring
spring:
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${username_}
    password: ${password}
  #    kafka:
  #      bootstrap-servers: localhost:9092

  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
# rabbitmq
#  rabbitmq:
#    host: localhost
#    username: guest
#    password: guest
#    port: 5672
#    eureka