pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/deploy#*']],
                    extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'Squad-service/.*']],
                    userRemoteConfigs: [[url: 'https://github.com/Hyedokal/GGWP.git']]
                ])
            }
        }
        stage('Gradle Build') {
            steps {
                dir('Squad-service') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }
        stage('Build and push Docker image') {
            steps {
                script {
                    dir('Squad-service') {
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                            def app = docker.build("hyedokal/ggwp_squad-service", "-f Dockerfile .")
                            app.push("latest")
                        }
                    }
                }
            }
        }
        stage('Deploy to EC2') {
            steps {
                dir('Squad-service') {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-34-3-159.ap-northeast-2.compute.amazonaws.com'
                            sudo docker stop \$(sudo docker ps -q) || true
                            sudo docker rm \$(sudo docker ps -a -q) || true
                            sudo docker rmi \$(sudo docker images -q) || true
                            sudo docker pull hyedokal/ggwp_squad-service:latest
                            sudo docker run -d -p 80:49870 hyedokal/ggwp_squad-service:latest
                        '
                    """
                }
            }
        }
    }
}