pipeline {
    agent any
    stages {

        stage('Deploy to EC2') {
            steps {
                dir('Squad-service') {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-34-3-159.ap-northeast-2.compute.amazonaws.com '
                            sudo docker stop \$(sudo docker ps -q) || true
                            sudo docker rm \$(sudo docker ps -a -q) || true
                            sudo docker rmi \$(sudo docker images -q) || true
                            sudo docker pull hyedokal/ggwp_squad-service:latest
                            sudo docker run -d -p 80:49870 hyedokal/ggwp_squad-service:latest
                        '
                    """
                }
            }
        }
    }
}