spring:
  datasource:
    driver-class-name: ${driver-class-name}
    url: jdbc:mysql://127.0.0.1:3306/devdb
    username: ${username_}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect