<<<<<<< HEAD
=======
spring:
  datasource:
    driver-class-name: ${driver-class-name}
    url: jdbc:mysql://127.0.0.1:3306/localdb
    username: ${username_}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
>>>>>>> 623e36e (Feat: 프론트 메인 Ui 수정)


