#server:
#  port: 0

spring:
  application:
    name: member-service
  profiles:
    active: db,jwt
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${username_}
    password: ${password}


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secretKey: helloworld
  access:
    expiration: 60
    header: Authorization
  refresh:
    expiration: 120
    header: Authorization
#
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true # ??? ??
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka # ??? ?? uri

