server:
  port: 8000

spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        # 이 밑에 본인의 Microservice 등록하기
        - id: squad-service
          uri: lb://SQUAD-SERVICE
          predicates:
            - Path=/Squad-service/**

        - id: Member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

